
import 'package:google_fonts/google_fonts.dart';
List fontFamilyList = [
  'Dancing Script',
  'Josefin Sans',
  'Anton',
  'Exo 2',
  'Pacifico',
  'Lobster',
  'Imbue',
  'Crimson Text',
  'Prompt',
  'Varela Round',
  'Licorice',
  'Play',
  'IBM Plex Mono',
  'Caveat',
  'Chakra Petch',
  'Shadows Into Light',
  'Abril Fatface',
  'Satisfy',
  'Lilita One',
  'Galada',
  'Permanent Marker',
  'Indie Flower',
  'Edu NSW ACT Foundation',
  'Orbitron',
  'Cinzel',
];