
import 'package:google_fonts/google_fonts.dart';
List fontFamilyList = [
  GoogleFonts.dancingScript,
  GoogleFonts.josefinSans,
  GoogleFonts.anton,
  GoogleFonts.exo2,
  GoogleFonts.pacifico,
  GoogleFonts.lobster,
  GoogleFonts.imbue,
  GoogleFonts.crimsonText,
  GoogleFonts.varelaRound,
  GoogleFonts.licorice,
  GoogleFonts.ibmPlexMono,
  GoogleFonts.caveat,
  GoogleFonts.chakraPetch,
  GoogleFonts.shadowsIntoLight,
  GoogleFonts.abrilFatface,
  GoogleFonts.satisfy,
  GoogleFonts.lilitaOne,
  GoogleFonts.galada,
  GoogleFonts.permanentMarker,
  GoogleFonts.indieFlower,
  GoogleFonts.permanentMarker,
  GoogleFonts.eduNswActFoundation,
  GoogleFonts.orbitron,
  GoogleFonts.cinzel,
];