import 'dart:ui';

Map image = {
  "color": [
    Color(0xff7fbffd),
    Color(0xfffff38d),
    Color(0xff57646d),
    Color(0xff577048),
    Color(0xff9bbaaa),
    Color(0xff9aafa0),
    Color(0xfff89e6c),
    Color(0xffa6e4b3),
    Color(0xffc9fff5),
    Color(0xffbfe0ff),
    Color(0xff97dafc),
    Color(0xff031d1c),
    Color(0xff445b6f),
  ],
  "affirmation": [
    'assets/project/affirmation/image1.jpeg',
    'assets/project/affirmation/image2.jpeg',
    'assets/project/affirmation/image3.jpeg',
    'assets/project/affirmation/image4.jpeg',
    'assets/project/affirmation/image5.jpeg',
    'assets/project/affirmation/image6.jpeg',
    'assets/project/affirmation/image7.jpeg',
    'assets/project/affirmation/image8.jpeg',
    'assets/project/affirmation/image9.jpeg',
    'assets/project/affirmation/image10.jpeg',
  ],
  "broken": [
    'assets/project/broken/image1.jpeg',
    'assets/project/broken/image2.jpeg',
    'assets/project/broken/image3.jpeg',
    'assets/project/broken/image4.jpeg',
    'assets/project/broken/image5.jpeg',
    'assets/project/broken/image6.jpeg',
    'assets/project/broken/image7.jpeg',
    'assets/project/broken/image8.jpeg',
    'assets/project/broken/image9.jpeg',
    'assets/project/broken/image10.jpeg',
  ],
  "deep": [
    'assets/project/deep/image1.jpeg',
    'assets/project/deep/image2.jpeg',
    'assets/project/deep/image3.jpeg',
    'assets/project/deep/image4.jpeg',
    'assets/project/deep/image5.jpeg',
    'assets/project/deep/image6.jpeg',
    'assets/project/deep/image7.jpeg',
    'assets/project/deep/image8.jpeg',
    'assets/project/deep/image9.jpeg',
    'assets/project/deep/image10.jpeg',
  ],
  "ego": [
    'assets/project/ego/image1.jpeg',
    'assets/project/ego/image2.jpeg',
    'assets/project/ego/image3.jpeg',
    'assets/project/ego/image4.jpeg',
    'assets/project/ego/image5.jpeg',
    'assets/project/ego/image6.jpeg',
    'assets/project/ego/image7.jpeg',
    'assets/project/ego/image8.jpeg',
    'assets/project/ego/image9.jpeg',
    'assets/project/ego/image10.jpeg',
  ],
  "friendship": [
    'assets/project/friendship/image1.jpeg',
    'assets/project/friendship/image2.jpeg',
    'assets/project/friendship/image3.jpeg',
    'assets/project/friendship/image4.jpeg',
    'assets/project/friendship/image5.jpeg',
    'assets/project/friendship/image6.jpeg',
    'assets/project/friendship/image7.jpeg',
    'assets/project/friendship/image8.jpeg',
    'assets/project/friendship/image9.jpeg',
    'assets/project/friendship/image10.jpeg',
  ],
  "funny": [
    'assets/project/funny/image1.jpeg',
    'assets/project/funny/image2.jpeg',
    'assets/project/funny/image3.jpeg',
    'assets/project/funny/image4.jpeg',
    'assets/project/funny/image5.jpeg',
    'assets/project/funny/image6.jpeg',
    'assets/project/funny/image7.jpeg',
    'assets/project/funny/image8.jpeg',
    'assets/project/funny/image9.jpeg',
    'assets/project/funny/image10.jpeg',
  ],
  "happy": [
    'assets/project/happy/image1.jpeg',
    'assets/project/happy/image2.jpeg',
    'assets/project/happy/image3.jpeg',
    'assets/project/happy/image4.jpeg',
    'assets/project/happy/image5.jpeg',
    'assets/project/happy/image6.jpeg',
    'assets/project/happy/image7.jpeg',
    'assets/project/happy/image8.jpeg',
    'assets/project/happy/image9.jpeg',
    'assets/project/happy/image10.jpeg',
  ],
  "hope": [
    'assets/project/hope/image1.jpeg',
    'assets/project/hope/image2.jpeg',
    'assets/project/hope/image3.jpeg',
    'assets/project/hope/image4.jpeg',
    'assets/project/hope/image5.jpeg',
    'assets/project/hope/image6.jpeg',
    'assets/project/hope/image7.jpeg',
    'assets/project/hope/image8.jpeg',
    'assets/project/hope/image9.jpeg',
    'assets/project/hope/image10.jpeg',
  ],
  "kindness": [
    'assets/project/kindness/image1.jpeg',
    'assets/project/kindness/image2.jpeg',
    'assets/project/kindness/image3.jpeg',
    'assets/project/kindness/image4.jpeg',
    'assets/project/kindness/image5.jpeg',
    'assets/project/kindness/image6.jpeg',
    'assets/project/kindness/image7.jpeg',
    'assets/project/kindness/image8.jpeg',
    'assets/project/kindness/image9.jpeg',
    'assets/project/kindness/image10.jpeg',
  ],
  "love": [
    'assets/project/love/image1.jpeg',
    'assets/project/love/image2.jpeg',
    'assets/project/love/image3.jpeg',
    'assets/project/love/image4.jpeg',
    'assets/project/love/image5.jpeg',
    'assets/project/love/image6.jpeg',
    'assets/project/love/image7.jpeg',
    'assets/project/love/image8.jpeg',
    'assets/project/love/image9.jpeg',
    'assets/project/love/image10.jpeg',
  ],
  "mental health": [
    'assets/project/mental health/image1.jpeg',
    'assets/project/mental health/image2.jpeg',
    'assets/project/mental health/image3.jpeg',
    'assets/project/mental health/image4.jpeg',
    'assets/project/mental health/image5.jpeg',
    'assets/project/mental health/image6.jpeg',
    'assets/project/mental health/image7.jpeg',
    'assets/project/mental health/image8.jpeg',
    'assets/project/mental health/image9.jpeg',
    'assets/project/mental health/image10.jpeg',
  ],
  "motivation": [
    'assets/project/motivation/image1.jpeg',
    'assets/project/motivation/image2.jpeg',
    'assets/project/motivation/image3.jpeg',
    'assets/project/motivation/image4.jpeg',
    'assets/project/motivation/image5.jpeg',
    'assets/project/motivation/image6.jpeg',
    'assets/project/motivation/image7.jpeg',
    'assets/project/motivation/image8.jpeg',
    'assets/project/motivation/image9.jpeg',
    'assets/project/motivation/image10.jpeg',
  ],
  "positive": [
    'assets/project/positive/image1.jpeg',
    'assets/project/positive/image2.jpeg',
    'assets/project/positive/image3.jpeg',
    'assets/project/positive/image4.jpeg',
    'assets/project/positive/image5.jpeg',
    'assets/project/positive/image6.jpeg',
    'assets/project/positive/image7.jpeg',
    'assets/project/positive/image8.jpeg',
    'assets/project/positive/image9.jpeg',
    'assets/project/positive/image10.jpeg',
  ],
  "sad": [
    'assets/project/sad/image1.jpeg',
    'assets/project/sad/image2.jpeg',
    'assets/project/sad/image3.jpeg',
    'assets/project/sad/image4.jpeg',
    'assets/project/sad/image5.jpeg',
    'assets/project/sad/image6.jpeg',
    'assets/project/sad/image7.jpeg',
    'assets/project/sad/image8.jpeg',
    'assets/project/sad/image9.jpeg',
    'assets/project/sad/image10.jpeg',
  ],
  "success": [
    'assets/project/success/image1.jpeg',
    'assets/project/success/image2.jpeg',
    'assets/project/success/image3.jpeg',
    'assets/project/success/image4.jpeg',
    'assets/project/success/image5.jpeg',
    'assets/project/success/image6.jpeg',
    'assets/project/success/image7.jpeg',
    'assets/project/success/image8.jpeg',
    'assets/project/success/image9.jpeg',
    'assets/project/success/image10.jpeg',
  ],
};
